package com.manuanand.photoshare;

import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.server.ResponseStatusException;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /user (after Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private PhotoRepository photoRepository;
	
	///
	// User Repository
	///
	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody User addUser (
			@RequestParam String name, @RequestParam String email, @RequestParam String password) {

		User newUser = new User();
		newUser.setName(name);
		newUser.setEmail(email);
		newUser.setPassword(password);
		
		userRepository.save(newUser);
		
		return newUser;
	}

	@GetMapping(path="/")
	public @ResponseBody Iterable<User> getAllUsers() {
		
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/{id}")
	public @ResponseBody User getSpecificUser(@PathVariable String id) {
		
		Integer userId = null;
		try {
			userId = Integer.parseInt(id);
		} catch (NumberFormatException ex) {
			return null;
		}

		Optional<User> user = userRepository.findById(userId);
		if (!user.isEmpty()) {
			return user.get();
		} 

		return null;
	}
	
	
	///
	// Photo Repository
	///
	@PostMapping(path="/upload") // Map ONLY POST Requests
	public @ResponseBody Photo addVideo (
			@RequestParam Integer userId, @RequestParam String password,
			@RequestParam String url, @RequestParam String title, 
			@RequestParam String description,
			@RequestParam (required = false) String commaSeparatedTags) {
		
		
		// Validate User
		Optional<User> user = userRepository.findById(userId);
		if (user.isEmpty()) {
			throw new ResponseStatusException(
					  HttpStatus.NOT_FOUND, "User with ID" + userId + " not found");
		} 
		
		if (!user.get().getPassword().equalsIgnoreCase(password)) {
			throw new ResponseStatusException(
					  HttpStatus.BAD_REQUEST, "Password mismatched for user with ID" + userId );
		} 

		Photo newVideo = new Photo();
		newVideo.setUrl(url);
		newVideo.setTitle(title);
		newVideo.setDescription(description);
		
		// Derived fields
		newVideo.setUploadedUserId(user.get().getId());
		newVideo.setUploadDate(new Date());
		newVideo.setNumRatings(0);
		newVideo.setRating(0);
		
		// Optional field
		newVideo.setCommaSeparatedTags(commaSeparatedTags);
		
		photoRepository.save(newVideo);
		
		return newVideo;
	}
}